package cn.et.test.entity;

public class Bibi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bibi.bid
     *
     * @mbg.generated Wed Dec 20 11:19:53 CST 2017
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bibi.bname
     *
     * @mbg.generated Wed Dec 20 11:19:53 CST 2017
     */
    private String bname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bibi.lid
     *
     * @mbg.generated Wed Dec 20 11:19:53 CST 2017
     */
    private Integer lid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bibi.bid
     *
     * @return the value of bibi.bid
     *
     * @mbg.generated Wed Dec 20 11:19:53 CST 2017
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bibi.bid
     *
     * @param bid the value for bibi.bid
     *
     * @mbg.generated Wed Dec 20 11:19:53 CST 2017
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bibi.bname
     *
     * @return the value of bibi.bname
     *
     * @mbg.generated Wed Dec 20 11:19:53 CST 2017
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bibi.bname
     *
     * @param bname the value for bibi.bname
     *
     * @mbg.generated Wed Dec 20 11:19:53 CST 2017
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bibi.lid
     *
     * @return the value of bibi.lid
     *
     * @mbg.generated Wed Dec 20 11:19:53 CST 2017
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bibi.lid
     *
     * @param lid the value for bibi.lid
     *
     * @mbg.generated Wed Dec 20 11:19:53 CST 2017
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }
}