package cn.et.test.entity.cook;



public class Cook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cook.fid
     *
     * @mbg.generated Wed Dec 13 16:36:58 CST 2017
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cook.fname
     *
     * @mbg.generated Wed Dec 13 16:36:58 CST 2017
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cook.cid
     *
     * @mbg.generated Wed Dec 13 16:36:58 CST 2017
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cook.fid
     *
     * @return the value of cook.fid
     *
     * @mbg.generated Wed Dec 13 16:36:58 CST 2017
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cook.fid
     *
     * @param fid the value for cook.fid
     *
     * @mbg.generated Wed Dec 13 16:36:58 CST 2017
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cook.fname
     *
     * @return the value of cook.fname
     *
     * @mbg.generated Wed Dec 13 16:36:58 CST 2017
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cook.fname
     *
     * @param fname the value for cook.fname
     *
     * @mbg.generated Wed Dec 13 16:36:58 CST 2017
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cook.cid
     *
     * @return the value of cook.cid
     *
     * @mbg.generated Wed Dec 13 16:36:58 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cook.cid
     *
     * @param cid the value for cook.cid
     *
     * @mbg.generated Wed Dec 13 16:36:58 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}