package cn.et.test.entity.cooking;

public class Cooking {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooking.cid
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooking.cname
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooking.kid
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    private Integer kid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooking.cid
     *
     * @return the value of cooking.cid
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooking.cid
     *
     * @param cid the value for cooking.cid
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooking.cname
     *
     * @return the value of cooking.cname
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooking.cname
     *
     * @param cname the value for cooking.cname
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooking.kid
     *
     * @return the value of cooking.kid
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public Integer getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooking.kid
     *
     * @param kid the value for cooking.kid
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public void setKid(Integer kid) {
        this.kid = kid;
    }
}