package cn.et.test.dao;

import java.util.List;
import java.util.Map;


import org.apache.ibatis.jdbc.SQL;

import cn.et.test.entity.cooking.Cooking;
import cn.et.test.entity.cooking.CookingExample;
import cn.et.test.entity.cooking.CookingExample.Criteria;
import cn.et.test.entity.cooking.CookingExample.Criterion;

public class CookingSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooking
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public String countByExample(CookingExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("cooking");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooking
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public String deleteByExample(CookingExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("cooking");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooking
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public String insertSelective(Cooking record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("cooking");
        
        if (record.getCid() != null) {
            sql.VALUES("cid", "#{cid,jdbcType=INTEGER}");
        }
        
        if (record.getCname() != null) {
            sql.VALUES("cname", "#{cname,jdbcType=VARCHAR}");
        }
        
        if (record.getKid() != null) {
            sql.VALUES("kid", "#{kid,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooking
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public String selectByExample(CookingExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("cid");
        } else {
            sql.SELECT("cid");
        }
        sql.SELECT("cname");
        sql.SELECT("kid");
        sql.FROM("cooking");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooking
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Cooking record = (Cooking) parameter.get("record");
        CookingExample example = (CookingExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("cooking");
        
        if (record.getCid() != null) {
            sql.SET("cid = #{record.cid,jdbcType=INTEGER}");
        }
        
        if (record.getCname() != null) {
            sql.SET("cname = #{record.cname,jdbcType=VARCHAR}");
        }
        
        if (record.getKid() != null) {
            sql.SET("kid = #{record.kid,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooking
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("cooking");
        
        sql.SET("cid = #{record.cid,jdbcType=INTEGER}");
        sql.SET("cname = #{record.cname,jdbcType=VARCHAR}");
        sql.SET("kid = #{record.kid,jdbcType=INTEGER}");
        
        CookingExample example = (CookingExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooking
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    public String updateByPrimaryKeySelective(Cooking record) {
        SQL sql = new SQL();
        sql.UPDATE("cooking");
        
        if (record.getCname() != null) {
            sql.SET("cname = #{cname,jdbcType=VARCHAR}");
        }
        
        if (record.getKid() != null) {
            sql.SET("kid = #{kid,jdbcType=INTEGER}");
        }
        
        sql.WHERE("cid = #{cid,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooking
     *
     * @mbg.generated Wed Dec 13 15:54:46 CST 2017
     */
    protected void applyWhere(SQL sql, CookingExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}